platform :ios, '10.0'
use_frameworks!

target ‘OneSwift’ do
        pod 'Alamofire', '~> 4.6’
	pod 'CryptoSwift’,’~> 0.7.2’
	pod 'SQLite.swift', '~> 0.11.4'
	pod 'SnapKit', '~> 4.0.0'
	
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = ‘4.0’
    end
  end
end
